### ISSUE TITLE
Home or Away game selection

### ISSUE THREAD

**Issue by Kilzzz** [tonycpsu/mlbstreamer#9]
Please implement a way to select the home or away feed from the command line.

**Comment by mkomko** [comment]
I implemented this for myself a few hours ago. It's really ugly since I just wanted to quickly hack it together and I'm not a Python developer.

I use the following code in play.main() to get the mediaId of the team passed via code:

        if schedule["dates"][0]["games"][0]["teams"]["away"]["team"]["id"] == teams[options.game]:
            home_away = "AWAY"
        else:
            home_away = "HOME"

        game_id = schedule["dates"][0]["games"][0]["gamePk"]
        media_items = schedule["dates"][0]["games"][0]["content"]["media"]["epg"][0]["items"]

        for media_item in media_items:
            if media_item["mediaFeedType"] == home_away:
                media_id = media_item["mediaId"]
                break

And then I pass the media_id to play_stream and use that. Ugly but it works for now :D.

**Comment by Kilzzz** [comment]
While its closed, I just want to thank mkomko for his help.

**Comment by mkomko** [comment]
Thanks, you're very welcome!
